// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofDwIz89YDH6AW64CFNorEpfrKn-hsfY',
    appId: '1:83127350834:web:d4b94eea668f22e9eb2e2b',
    messagingSenderId: '83127350834',
    projectId: 'redify-12c06',
    authDomain: 'redify-12c06.firebaseapp.com',
    storageBucket: 'redify-12c06.firebasestorage.app',
    measurementId: 'G-KMN9C82WR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfAHIrgoZP3gejhDB6tfDfLOXFgSR-IgQ',
    appId: '1:83127350834:android:9d24676ac4be7a02eb2e2b',
    messagingSenderId: '83127350834',
    projectId: 'redify-12c06',
    storageBucket: 'redify-12c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwJTtbwEUT-B4L62F38a0o5iRKECtFHY',
    appId: '1:83127350834:ios:6402954a5dd94744eb2e2b',
    messagingSenderId: '83127350834',
    projectId: 'redify-12c06',
    storageBucket: 'redify-12c06.firebasestorage.app',
    iosBundleId: 'com.example.readify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwJTtbwEUT-B4L62F38a0o5iRKECtFHY',
    appId: '1:83127350834:ios:6402954a5dd94744eb2e2b',
    messagingSenderId: '83127350834',
    projectId: 'redify-12c06',
    storageBucket: 'redify-12c06.firebasestorage.app',
    iosBundleId: 'com.example.readify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAofDwIz89YDH6AW64CFNorEpfrKn-hsfY',
    appId: '1:83127350834:web:29827550bae24605eb2e2b',
    messagingSenderId: '83127350834',
    projectId: 'redify-12c06',
    authDomain: 'redify-12c06.firebaseapp.com',
    storageBucket: 'redify-12c06.firebasestorage.app',
    measurementId: 'G-MNYGG9HF2Y',
  );
}
